# ISC Platform Configuration
platform.host=172.16.18.85
platform.port=443
platform.appKey=27133966
platform.appSecret=aTbADLtEFsjhSHCNIXuO
platform.userId=openclaw03
platform.domainId=domain0
# 平台外网地址（用于前端页面跳转）
platform.externalUrl=https://isc02.bjzatx.com
